loaders:
  - type: deepstack_pydoc_tools.loaders.CustomPythonLoader
    search_path: [../src]
    modules:
      [
        "deepstack_integrations.components.retrievers.qdrant.retriever",
        "deepstack_integrations.document_stores.qdrant.document_store",
        "deepstack_integrations.document_stores.qdrant.migrate_to_sparse",
      ]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: deepstack_pydoc_tools.renderers.ReadmePreviewRenderer
  excerpt: Qdrant integration for Deepstack
  category_slug: integrations-api
  title: Qdrant
  slug: integrations-qdrant
  order: 210
  markdown:
    descriptive_class_title: false
    classdef_code_block: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: _readme_qdrant.md
